apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-app-deployment-1
  template:
    metadata:
      labels:
        app: dev-app-deployment-1
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-deployment-1-svc
spec:
  type: ClusterIP
  selector:
    app: dev-app-deployment-1
  ports:
    - port: 80
      targetPort: 80
