apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-app-deployment-1
  template:
    metadata:
      labels:
        app: dev-app-deployment-1
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              echo "Hello from pod $(POD_NAME)" > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: app-deployment-1-svc
spec:
  type: NodePort
  selector:
    app: dev-app-deployment-1
  ports:
    - port: 80
      targetPort: 80
