apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deployment-app1
  template:
    metadata:
      labels:
        app: nginx-deployment-app1
    spec:
      containers:
        - name: app1
          image: capnandan/nginx:app1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-app1-svc
spec:
  type: ClusterIP
  selector:
    app: nginx-deployment-app1
  ports:
    - port: 80
      targetPort: 80